import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950`}
      >
        <nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-center p-4 bg-zinc-950/80 backdrop-blur-sm border-b border-zinc-900">
          <div className="flex gap-6 text-sm font-medium">
            <a href="/" className="text-zinc-400 hover:text-white transition-colors">Summarizer</a>
            <a href="/mask" className="text-zinc-400 hover:text-white transition-colors">Mask Prediction</a>
          </div>
        </nav>
        <div className="pt-16">
          {children}
        </div>
      </body>
    </html>
  );
}
